services:
  app:
    image: us-docker.pkg.dev/send-it-digital/docker-1/send-it-digital-crossroads:${GH_REF}
    build: .
    container_name: send-it-digital-crossroads
    volumes:
      - ./${GOOGLE_APPLICATION_CREDENTIALS}:/tmp/${GOOGLE_APPLICATION_CREDENTIALS}
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/${GOOGLE_APPLICATION_CREDENTIALS}
      K_SERVICE: dev
      K_CONFIGURATION: dev
      K_REVISION: dev-00001

      PUBLIC_URL: ${PUBLIC_URL}
    ports:
      - 8080:8080
